### PR TITLE
Refactor visitor pages

### PR DESCRIPTION
**Pull request by rbaggio018**

### CODE REVIEW

**Review by panyachen — COMMENTED** [review]
Awesome! the code looks good to me. Will do some tests later tomorrow. Thanks

**Comment by panyachen** [comment]
I will merge the pull request after testing being done.

**Review by panyachen — COMMENTED** [review]
adding page cache to public, do we need to deal explicitly with cache expiration "sweep" issue?

**Comment by rbaggio018** [comment]
Good question about cache expiration. Those static pages will be expired every time we deploy.

**Comment by panyachen** [comment]
Reporting several issues:
1. mobile-size nav menu is not working properly on all pages.
2.  学员指南 and teacher faq page：collapse all doesn't work properly. single collapse has issue with up/down arrow.
     please see the right behavior in mspan.cn
3.  teacherhome page footer FAQ fails to link to teacher faq page.

**Comment by rbaggio018** [comment]
1. mobile可能你得跟我讲一下，主要原因是有人手动改过你用的那个bootstrap.css。我们可能花时间修一下。
2. good catch. there's a bug which makes it stop working when navigate around. fixed. btw, mspan.cn有个小问题，第一次点小箭头的时候，箭头方向不动。我把整个方向反过来了。
3. good catch. fixed.

**Pull request merged**
